name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "Docs/**"
  repository_dispatch:
    types: [Docs]
  gollum:

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: Docs
          destination: wiki
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }} # allows us to push back to repo
          ref: develop
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: develop # since default branch is develop in this example

  # You may pin to the exact commit or the version.
  # uses: newrelic/wiki-sync-action@dbf2a9603687e77ad8b5be714fa6dd055183508b
  uses: newrelic/wiki-sync-action@v1.0.1
  with:
    # Source directory/location of file sync (ex: `docs`).
    source: 
    # Destination directory/location for file sync (ex: `wiki`).
    destination: 
    # Github personal access token with at least 'repo' authorization.
    token: 
    # Author name to use for committing to repository. Default: `github.actor`
    gitAuthorName: # optional, default is ${{ github.actor }}
    # Author name to use for committing to repository. Default: `github.actor@users.noreply.github.com
    gitAuthorEmail: # optional
    # Default branch to commit to. Default: `master`
    branch: # optional, default is master
    # Message for committing files to repository.
    commitMessage: # optional
          
