name: Update Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Debug: List repository contents
      - name: List Repository Contents
        run: |
          echo "Repository structure:"
          ls -R

      # Check for the docs folder
      - name: Verify docs Folder
        run: |
          if [ ! -d "docs" ]; then
            echo "Error: 'docs' folder not found. Skipping sync."
            exit 0
          fi

      # Set up Git configuration
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Sync docs folder to the Wiki
      - name: Sync docs to Wiki
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          rsync -av --delete docs/ wiki/
          cd wiki
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update Wiki from docs folder"
            git push
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
